---
# To set roles for down steps
# ansible-galaxy init spark_master
# ansible-galaxy init splunk.splunk
# ansible-galaxy init geerlingguy.jenkins

- name: Install and configure dependencies
  hosts: all
  become: true
  tasks:
    - name: Install security updates on Rocky Linux 9
      yum:
        name: '*'
        state: latest
      when: ansible_distribution == 'Rocky' and ansible_distribution_major_version == '9'

    # Set firewall ports
    - name: Open firewall ports for necessary services
      firewalld:
        port: "{{ item }}/tcp"
        state: enabled
        immediate: yes
      loop:
        - 8080  # Jenkins
        - 9997  # Splunk forwarder data
        - 50070 # Spark Master web UI
        - 7077  # Spark Master RPC
        - 8081  # Spark Worker web UI
        - 5432  # PostgreSQL

    # Install and config JaVa
    - name: Install OpenJDK
      yum:
        name: java-1.8.0-openjdk
        state: present
    - name: Set JAVA_HOME for OpenJDK
      lineinfile:
        dest: /etc/environment
        line: 'JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.402.b06-1.el7_9.x86_64/'
        state: present
      become: true

    # Install and config python3
    - name: Install Python 3.11
      yum:
        name: [epel-release, yum-utils, python3, python2]
        state: present

    # Install and configure Splunk
    # TODO: fix this  + configurations
    - name: Install Splunk
      include_role:
        name: splunk.splunk
    - name: Enable Splunk to start on boot
      service:
        name: splunk
        enabled: yes
        state: started

    # Install and configure Jenkins
    - name: Add Jenkins repository key
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat/jenkins.io.key
    - name: Add Jenkins repository
      yum_repository:
        name: jenkins
        description: Jenkins Official Repository
        baseurl: https://pkg.jenkins.io/redhat-stable
        gpgcheck: yes
        enabled: yes
    - name: Install Jenkins
      package:
        name: jenkins
        state: present

    # Install and configure Spark Master
    # TODO: fix this  + configurations
    - name: Install Spark Master
      yum:
        name: spark-master
        state: present
    - name: Configure Spark Master
      template:
        src: spark-master.conf.j2
        dest: /etc/spark/spark-master.conf
      notify:
        - restart spark master
    - name: Start Spark Master as systemd service
      systemd:
        name: spark-master
        state: started
        enabled: yes

    # Install and configure Spark Worker
    - name: Install Spark Worker
      yum:
        name: spark-worker
        state: present
    - name: Configure Spark Worker
      template:
        src: spark-worker.conf.j2
        dest: /etc/spark/spark-worker.conf
      notify:
        - restart spark worker
    - name: Start Spark Worker as systemd service
      systemd:
        name: spark-worker
        state: started
        enabled: yes

    # Install and configure Spark Worker
    # TODO: fix this  + configurations
    - name: Install Spark Driver
      yum:
        name: spark-driver
        state: present
    - name: Configure Spark Driver
      template:
        src: spark-driver.conf.j2
        dest: /etc/spark/spark-driver.conf

    # Install and configure PostgreSQL
    - name: Install PostgreSQL
      yum:
        name: postgresql
        state: present
    - name: Configure PostgreSQL
      template:
        src: postgresql.conf.j2
        dest: /etc/postgresql/postgresql.conf
      notify:
        - restart postgresql
    - name: Create user with all privileges on all databases
      postgresql_user:
        name: admin_user
        password: "{{ admin_user_password }}"
        priv: "*.*:ALL"
    - name: Create user with read-only privileges on all databases
      postgresql_user:
        name: read_only_user
        password: "{{ read_only_user_password }}"
        priv: "*.*:SELECT"
    - name: Start PostgreSQL as systemd service
      systemd:
        name: postgresql
        state: started
        enabled: yes
